version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: smarttaskmanager-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - smarttaskmanager-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Password123 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 40s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smarttaskmanager-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=SmartTaskManager;User=sa;Password=YourStrong!Password123;TrustServerCertificate=true;
    ports:
      - "8080:80"
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - smarttaskmanager-network

volumes:
  sqlserver_data:

networks:
  smarttaskmanager-network:
    driver: bridge